# Schema for the configuration files of the VSCPA SSO(Gluu Server) module.
vscpa_sso.settings:
  type: config_object
  label: 'Gluu SSO settings'
  mapping:
    api_provider_url:
      type: string
      label: 'Gluu Server API Provider Url'
    api_client_id:
      type: string
      label: 'Gluu Server Client ID'
    api_client_secret:
      type: string
      label: 'Gluu Server Client Secret'