<?php

/**
 * @file
 * Provides enhancements for implementing VSCPA migrations.
 */

use Drupal\migrate\Row;
use Drupal\Core\Form\FormStateInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;

/**
 * Implements hook_migrate_prepare_row().
 */
function vscpa_content_migration_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // Note: The migration will to skip the row if any hook_migrate_prepare_row
  // returned FALSE.
  if (in_array($migration->id(), ['article_node', 'topic_node'])) {
    $info = [];
    $article_tid = 15312;
    $topic_tid = 15311;
    // Field Pub Type.
    $pub_type = ($migration->id() == 'article_node') ? $article_tid : $topic_tid;
    $info['pub_type'] = $pub_type;
    $row->setSourceProperty('pub_type', $pub_type);
    // Field ID.
    $id = $row->getSourceProperty('id');
    $info['id'] = $id;
    // Field Name.
    $name = $row->getSourceProperty('name');
    $info['name'] = $name;
    // Field Description.
    $description = $row->getSourceProperty('description');
    $info['description'] = $description;
    // Field Last Publication Status.
    $publish = $row->getSourceProperty('last_publication_status');
    $status = 0;
    if (strtolower($publish) == 'page published') {
      $status = 1;
    }
    $row->setSourceProperty('last_publication_status', $status);
    $info['publish'] = $publish;
    // Field: Last Status Changes.
    $last_status_changes = $row->getSourceProperty('last_status_changes');
    $info['last_status_changes'] = $last_status_changes;
    // Field: Is Parent.
    $is_parent = $row->getSourceProperty('is_parent');
    $info['is_parent'] = $is_parent;
    // Field: Modified Date Time.
    $modified_date_time = $row->getSourceProperty('modified_date_time');
    $info['modified_date_time'] = $modified_date_time;
    // Field: Created Date Time.
    $created_date_time = $row->getSourceProperty('created_date_time');
    $info['created_date_time'] = $created_date_time;
    // Field: Friendly Url.
    $friendly_url = $row->getSourceProperty('friendly_url');
    $info['friendly_url'] = $friendly_url;
    // Field: Alternative Text.
    $alternative_text = $row->getSourceProperty('alternative_text');
    $info['alternative_text'] = $alternative_text;
    // Field: Title.
    $title = $row->getSourceProperty('title');
    if (empty($title) && !empty($name)) {
      $title = $name;
      $row->setSourceProperty('title', $title);
    }
    $info['title'] = $title;
    // Field: Link Url.
    $link_url = $row->getSourceProperty('link_url');
    $info['link_url'] = $link_url;
    // Field: Summary.
    $summary = $row->getSourceProperty('summary');
    $info['summary'] = $summary;
    // Field: Keywords.
    $keywords = $row->getSourceProperty('keywords');
    $info['keywords'] = $keywords;
    // Field: Content.
    $body = $row->getSourceProperty('body');
    $info['body'] = $body;
    // Field Old Path.
    $old_url = "https://www.vscpa.com/content/{$id}.aspx";
    $row->setSourceProperty('field_oldpath_uri', $old_url);
    $info['field_old_path'] = $old_url;
    // Print Result.
    // drush_print(json_encode($info));.
  }
}

/**
 * Implements hook_form_alter().
 */
function vscpa_content_migration_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id = 'views_form_content_page_1' && (isset($form['body_value_op']['#title']))) {
    $form['body_value_op']['#title'] = t('Body');
  }
}
