---

- name: Check that dhparam.pem exists (used for TLS configuration)
  stat:
    path: /etc/ssl/nginx/dhparam.pem
  register: dhparam_exists
  become: yes
  tags:
    - nginx
    - tls
- name: Ensure NGINX TLS directory exists with proper permissions
  file:
    path: /etc/ssl/nginx
    state: directory
    owner: root
    group: root
  become: yes
  tags:
    - nginx
    - tls
- name: Generate dhparam.pem if not already present (this will take a long time)
  command: openssl dhparam -out /etc/ssl/nginx/dhparam.pem 4096
  when: dhparam_exists.stat.exists == False
  become: yes
  tags:
    - nginx
    - tls
- name: Copy TLS certificate and key
  copy:
    content: "{{ item.content }}"
    dest: "/etc/ssl/sites/{{ item.site }}/{{ item.name }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o="
  with_items:
    - "{{ certificates }}"
  notify:
    - validate nginx configuration
    - reload nginx
  become: true
  tags:
    - nginx
    - tls
