field.formatter.settings.vscpa_commerce_current_price:
  type: mapping
  label: 'Default price formatter settings'
  mapping:
    strip_trailing_zeroes:
      type: boolean
      label: 'Strip trailing zeroes after the decimal point'
    display_currency_code:
      type: boolean
      label: 'Display the currency code instead of the currency symbol'
