<?php

/**
 * @file
 * Contains am_net_firms.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;

/**
 * Implements hook_theme().
 */
function am_net_firms_theme() {
  return [
    'modal_registration' => [
      'variables' => [
        'show_variation_selector' => FALSE,
        'selected_variation_id' => NULL,
        'employees' => '',
        'sessions' => '',
        'variations' => [],
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function am_net_firms_taxonomy_term_update(EntityInterface $term) {
  $firm_manager = \Drupal::service('am_net_firms.firm_manager');
  if (($term->bundle() == 'firm') && $firm_manager->isFirmAvailableForSync($term)) {
    $patterns = "/taxonomy/term/*/edit";
    $current_path = \Drupal::service('path.current')->getPath();
    $match = \Drupal::service('path.matcher')->matchPath($current_path, $patterns);
    if (!$match) {
      // Add Firm term for update their info on AMNet.
      $result = $firm_manager->updateFirmRecordFormTerm($term);
    }
  }
}

/**
 * Implements hook_entity_form_display_alter().
 */
function am_net_firms_entity_form_display_alter(EntityFormDisplayInterface &$form_display, array $context) {
  if ($context['entity_type'] == 'taxonomy_term' && $context['bundle'] == 'firm') {
    $user = \Drupal::currentUser();
    $is_admin = in_array('administrator', $user->getRoles());
    $is_firm_administrator = in_array('firm_administrator', $user->getRoles());
    /* @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface $storage */
    $storage = \Drupal::service('entity_type.manager')->getStorage('entity_form_display');
    if (!$is_admin && $is_firm_administrator) {
      $form_display = $storage->load('taxonomy_term.firm.edit_firm_info');
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function am_net_firms_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_form_find_employees_default') {
    $form['actions']['submit']['#value'] = t('Add Selected to Your Firm/Company');
    $form['header']['user_bulk_form']['#attributes']['class'][] = 'hide';
    $form['actions']['submit']['#attributes']['class'][] = 'btn-purple';
  }
  if ($form_id == 'taxonomy_term_firm_form') {
    $form['actions']['submit']['#value'] = t('Update');
    if (isset($form['relations'])) {
      $user = \Drupal::currentUser();
      $is_admin = in_array('administrator', $user->getRoles());
      $is_firm_administrator = in_array('firm_administrator', $user->getRoles());
      if (!$is_admin && $is_firm_administrator) {
        $form['relations']['#access'] = FALSE;
      }
    }
  }
  if (($form_id == 'views_exposed_form') && ($form['#id'] == 'views-exposed-form-find-employees-default')) {
    $route_match = \Drupal::routeMatch();
    $user = $route_match->getParameter('user');
    $firm = $route_match->getParameter('firm');
    if ($user && $firm) {
      $add_new_employee_url = Url::fromRoute('am_net_firms.employee_management_tool.add_employees', [
        'user' => $user->id(),
        'firm' => $firm->id(),
      ])->toString();
      $form['title'] = [
        '#type' => 'item',
        '#markup' => '<p class="accent-left purple">Use the fields below to search for an employee</p>',
        '#weight' => -40,
      ];
      $add_new_employee = '<div class="col-xs-12 col-lg-6"><div class="section last"><h3 class="accent-left gold">Create New Employee</h3><p>If unable to locate an employee with the Find Employee search, you may create an employee by clicking the button below and completing a short form.</p><a class="btn btn-gold" href="' . $add_new_employee_url . '">Create New Employee <span class="icon-plus" aria-hidden="true"></span></a></div></div>';
      $form['#attributes']['class'][] = 'form-find-employees';
      $form['#prefix'] = '<div class="col-xs-12 col-lg-6">';
      $form['#suffix'] = '</div>' . $add_new_employee;
      $form['actions']['submit']['#attributes']['class'][] = 'btn-purple';
      $form['last_name']['#title'] = 'Last Name';
      $form['actions']['submit']['#value'] = 'Search Now';
      // Hide Keywords.
      hide($form['keywords']);
    }
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function am_net_firms_preprocess_views_view(&$variables) {
  if ($variables['id'] != 'find_employees') {
    return;
  }
  if (!isset($variables['empty'])) {
    return;
  }
  if (empty($variables['empty'])) {
    return;
  }
  \Drupal::messenger()->addWarning(t('<strong>No users could be found matching your criteria.</strong>'));
}
