<?php

/**
 * @file
 * VSCPA Events module.
 */

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function vscpa_events_commerce_product_load($entities) {
  /** @var \Drupal\vscpa_events\EventsHelperInterface $helper */
  $helper = \Drupal::service('vscpa_events.events_helper');
  foreach ($entities as $entity) {
    if ($helper->isConference($entity) && $webcast = $helper->getRelatedWebcast($entity)) {
      $entity->related_webcast = $webcast;
    }
    if ($helper->isWebcast($entity) && $conference = $helper->getRelatedConference($entity)) {
      $entity->related_conference = $conference;
    }
  }
}
