---

- name: Ensure NFS is supported
  apt:
    name: nfs-client
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - nfs
    - nfs-client
- name: Ensure NFS mount point directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ nfs_shared_directories }}"
  become: yes
  tags:
    - nfs
    - nfs-client
- name: Ensure NFS mounts are configured
  mount:
    src: "vscpa-datastore0:{{ item }}"
    path: "{{ item }}"
    fstype: nfs4
    opts: "auto,nofail,noatime,nolock,intr,tcp,rw,actimeo=5,lookupcache=pos"
    state: mounted
  with_items: "{{ nfs_shared_directories }}"
  become: yes
  tags:
    - nfs
    - nfs-client
