<?php

/**
 * @file
 * Module for adding styles to admin theme.
 */

/**
 * Implements hook_foo().
 */
function vscpa_admin_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);

  if ($is_admin) {
    $library = [
      '#attached' => [
        'library' => [
          'vscpa_admin/vscpa_admin',
        ],
      ],
    ];

    \Drupal::service('renderer')->render($library);
  }
}
