# Schema for the configuration files of the (AMS) AM.net modules.
am_net.settings:
  type: config_object
  label: '(AMS) AM.net settings'
  mapping:
    api_prod_base_url:
      type: string
      label: '(AMS) AM.net API Integration Production Base Url'
    api_prod_auth_user:
      type: string
      label: '(AMS) AM.net API Integration Production User'
    api_prod_auth_key:
      type: string
      label: '(AMS) AM.net API Integration Production Key'
    api_dev_base_url:
      type: string
      label: '(AMS) AM.net API Integration Development Base Url'
    api_dev_auth_user:
      type: string
      label: '(AMS) AM.net API Integration Development User'
    api_dev_auth_key:
      type: string
      label: '(AMS) AM.net API Integration Development Key'
    cron:
      type: boolean
      label: 'Queue subscription operations for cron'
    batch_limit:
      type: integer
      label: 'Batch limit'
    connection_environment:
      type: string
      label: 'Whether (AMS) AM.net API send is currently in test mode'