am_net_membership.billing_class_checker_manager:
  type: config_entity
  label: 'Billing Class Checker Manager configuration'
  mapping:
    default_checker_id:
      type: string
      label: 'Default checker ID'
    license_expiration_month:
      type: string
      label: 'License expiration month'
    license_expiration_day:
      type: string
      label: 'License expiration day of the month'
    membership_renewal_on_days_left:
      type: integer
      label: 'Membership renewal on days left'
