name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: docker://sonarsource/sonar-scanner-cli:latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GTOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: TEST IF PASSED OR FAIL
        run: |
            echo "result=FAIL" >> $GITHUB_ENV

      - name: ECHO TESTING
        run: echo "${{ env.result }}" 

      - name: PASS
        if: "${{ env.result }}" == "OK"
        run: echo "DONE" 

      - name: FAIL
        if: "${{ env.result }}" == "FAIL"
        run: echo "NOT DONE" 
           # echo "result=$(curl -u admin:admin@123 http://13.232.220.12:9000/api/qualitygates/project_status?projectKey=action-demo | jq '.projectStatus.status' | tr -d '"')" >> $GITHUB_ENV
