name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: TEST IF SONAR PASS OR  FAIL
        run: |
            echo "result=ERROR" >> $GITHUB_ENV

      - name: ECHO TESTING OUTPUT
        run: echo "${{ env.result }}" 

      - name: PASS
        if: ${{ env.result  == 'OK' }}
        run: echo "PASSED" 

      - name: FAIL
        if: ${{ env.result  == 'ERROR' }}
        run: |
          echo "SONARQUBE CODE QUALITY GATES FAILED" 
          exit 1
          