name: CI/CD counter app
on:
  push:
    branches: [ main ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:


      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/action-demo
            git pull origin main

      # - name: Checkout the code
      #   uses: actions/checkout@v2
      #   with:
      #    # repository: ${{org}}/repositoryA
      #     ref: main
      # #    token: ${{ secrets.token }}
      #   #  persist-credentials: false
      #  #   path: ./github-app-jwt-action
      #     dir: /home/ubuntu/action
